spring.application.name=VedicVastram
spring.datasource.url=jdbc:h2:mem:kurti_db
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
server.port=8080
jwt.secret=ThisIsMyVerySecureSecretKeyFor256BitHS256Algorithm
jwt.expiration=86400000